#!/bin/sh

echo "---------"
echo "*** Clearing keyboard Caches ***"

/bin/rm -rf /var/mobile/Library/Caches/com.apple.keyboards/

echo ""
echo "*** Follow me on twitter @moeseth ***"
echo "---------"
echo " "
echo "Respring Now!!!"
echo "Respring Now!!!"
echo ""
exit 0;